### ISSUE TITLE
new commit doesnt build on debian 9

### ISSUE THREAD

**Issue by barhom** [gfto/tomcast#5]
It doesn't build because of;

> 
> /tomcast# make
>   CC	tomcast		web_pages.c
> In file included from web_pages.c:31:0:
> config.h:84:2: error: unknown type name ‘bool’
>   bool    allow_encrypted_input;
>   ^

#include <stdbool.h>
in config.h fixes it.

**Comment by gfto** [comment]
Fixed in current master.
